### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by BirdNerdW** [reidtreharne/Navigation3D#2]
I would really like to use this plugin. However, after I select to rebuild I get another error saying it couldn't be compiled and to try rebuilding from source manually. I just updated to UE 4.26 and tried it on both my existing and a new project with no success.

**Comment by macdonaldj** [comment]
same, any work arounds?

**Comment by BirdNerdW** [comment]
Sorry for the late reply. I didn't figure anything out.

**Comment by ZacharyDK** [comment]
Go to the Uplugin file and modify the whitelist and blacklist platforms. I had to add Mac to the whitelist and remove it from the blacklist. It compiled fine on mac.

**Comment by holger-dev** [comment]
I cant compile it with UE5 Preview 2 :( Any hints?

**Comment by holger-dev** [comment]
Ok, solved by reinstalling Net SDK 6, Net 6 itself, dotnet and VSCode with C++-Tools. Than, recompiling runs :) - THX!

**Comment by gothicserpent** [comment]
> Ok, solved by reinstalling Net SDK 6, Net 6 itself, dotnet and VSCode with C++-Tools. Than, recompiling runs :) - THX!

Would be great if you could close the issue..

**Comment by gothicserpent** [comment]
>  I would really like to use this plugin. However, after I select to rebuild I get another error saying it couldn't be compiled and to try rebuilding from source manually. I just updated to UE 4.26 and tried it on both my existing and a new project with no success.

Seems like people are able to get this to compile in 5.2.1 (worked for me with no code changes).

Would be appropriate to close this.

I also got Navigation3D fully working in my 6dof game and want to thank the author. Thank you for your work.

**Comment by reidtreharne** [comment]
@gothicserpent No problem 👍 I'll mark this as closed.
